services:
  ms1-productos:
    image: jesval06/shopcloud-ms1-productos:latest
    container_name: ms1-productos
    restart: unless-stopped
    env_file:
      - .env.ms1
    ports:
      - "8001:8001"
    networks:
      - shopcloud-net
  
  ms2-pedidos:
    image: jesval06/shopcloud-ms2-pedidos:latest
    container_name: ms2-usuarios
    restart: unless-stopped
    env_file:
      - .env.ms2
    ports:
      - "8002:8002"
    networks:
      - shopcloud-net
  
  ms3-usuarios:
    image: jesval06/shopcloud-ms3-usuarios:latest
    container_name: ms3-pedidos
    restart: unless-stopped
    env_file:
      - .env.ms3
    ports:
      - "8003:8003"
    networks:
      - shopcloud-net

  ms4-historial:
    image: jesval06/shopcloud-ms4-historial:latest
    container_name: ms4-historial
    restart: unless-stopped
    env_file:
      - .env.ms4
    ports:
      - "8004:8004"
    networks:
      - shopcloud-net

networks:
  shopcloud-net:
    driver: bridge
